Test

diff --git a/.github/workflows/scan.yml b/.github/workflows/scan.yml
--- a/.github/workflows/scan.yml
+++ b/.github/workflows/scan.yml
@@ -1,29 +1,39 @@
-name: CI-BlackDuck-SCA
+name: CI-BlackDuck-SCA-Basic
 on:
   push:
     branches: [ main, master, develop, stage, release ]
   pull_request:
     branches: [ main, master, develop, stage, release ]
   workflow_dispatch:
-    
+
 jobs:
   build:
-    runs-on: ubuntu-latest
+    runs-on: [ ubuntu-latest ]
     steps:
       - name: Checkout Source
         uses: actions/checkout@v3
 
-      - name: Run Black Duck Scan
+      - name: Black Duck Scan
+        uses: blackduck-inc/black-duck-security-scan@v2.0.0
+
+        env:
+          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
+
+        with:
+          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
+          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
         id: blackduck_scan
         continue-on-error: true
-        with:
-          blackducksca_url: ${{ vars.BLACKDUCK_URL }}
-          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
-        uses: blackduck-inc/black-duck-security-scan@v2.0.0
+
+      - name: Capture Black Duck Scan Exit Code
         run: |
-          exitcode="$?"
-          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-          exit "$exitcode"
+            EXIT_CODE=$?
+            echo "Exit Code from Black Duck Scan: $EXIT_CODE"
+            echo "BLACKDUCK_EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV
+            if [[ $EXIT_CODE -ne 0 ]]; then
+              echo "Scan failed with exit code $EXIT_CODE"
+              exit $EXIT_CODE
+            fi
 
       - name: Evaluate Scan Exit Code
         run: |
